database_migration:
  stage: migrate
  script:
    # 1. Pastikan folder bersih dari file root di awal
    - sudo chown -R gitlab-runner:gitlab-runner .
    
    # 2. Jalankan migrasi
    - |
      docker run --rm \
        -v "$(pwd):/app" \
        -w /app \
        -e DATABASE_URL="$DATABASE_URL" \
        node:22-alpine \
        sh -c "
          npm install --silent --no-progress && 
          npx prisma migrate resolve --applied 000_init_baseline || true &&
          npx prisma migrate deploy
        "
    
    # 3. Bereskan izin lagi setelah selesai
    - sudo chown -R gitlab-runner:gitlab-runner .
  only:
    - main
  when: manual